version: '3'
services:
  postgres-container:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d/
  backend-container:
    image: backend
    ports:
      - 3000:3000
  frontend-container:
    image: frontend
    ports:
      - 4200:4200
volumes:
  postgres-data:
    driver: local
